CREATE PROC FI_SP_AltBeneficiario
    @NOME          VARCHAR (50),
	@CPF           VARCHAR (14),
	@IDCLIENTE     BIGINT,
	@ID            BIGINT
AS
BEGIN
	UPDATE BENEFICIARIOS
	SET 
		NOME = @NOME, 
		CPF = @CPF
	WHERE Id = @Id AND IDCLIENTE = @IDCLIENTE
END